# Generated by Django 5.2.11 on 2026-02-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['customer__name', 'sku']},
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('customer', 'sku'), name='uniq_product_customer_sku'),
        ),
    ]
